apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
    name: instrumentation-3090
spec:
  exporter:
    endpoint: http://10.177.21.35:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: always_on
