apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: my-instrumentation
spec:
  exporter:
    endpoint: http://otel-daemonset-collector:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: always_on
