apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-daemonset
spec:
  mode: daemonset
  hostNetwork: true
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      filter/1:
        spans:
          exclude:
            match_type: strict
            attributes:
              - Key: thread.name
                Value: Nacos-Watch-Task-Scheduler-1
    exporters:
      otlp:
        endpoint: "http://tempo:4317"
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [filter/1]
          exporters: [otlp]
